### ISSUE TITLE
运行bert_whitening.py时报错

### ISSUE THREAD

**Issue by ryy980622** [JarenceSJ/ReviewGraph#2]
你好，我非常喜欢你的工作，并按照指导下载了数据集并成功运行了Word2vector.py和load_data.py，但是在初始化review embedding的时候bert_whitening.py报如下的错误，请问可以帮忙看一下吗，非常感谢！
Traceback (most recent call last):
  File "bert_whitening.py", line 169, in <module>
    save_sentence_feat(args)
  File "/home/ryy/anaconda3/envs/RGCL/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "bert_whitening.py", line 142, in save_sentence_feat
    for u, i, r, input_ids, mask in tqdm(data_loader):
  File "/home/ryy/anaconda3/envs/RGCL/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/ryy/anaconda3/envs/RGCL/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/ryy/anaconda3/envs/RGCL/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ryy/anaconda3/envs/RGCL/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "bert_whitening.py", line 93, in collate_fn
    encoding = bert_tokenizer(tokens, return_tensors='pt', padding=True,
  File "/home/ryy/anaconda3/envs/RGCL/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2477, in __call__
    return self.batch_encode_plus(
  File "/home/ryy/anaconda3/envs/RGCL/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2668, in batch_encode_plus
    return self._batch_encode_plus(
  File "/home/ryy/anaconda3/envs/RGCL/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 728, in _batch_encode_plus
    ids, pair_ids = ids_or_pair_ids
ValueError: too many values to unpack (expected 2)

**Comment by JarenceSJ** [comment]
看样子报错是在 bert_whitening.py 93 行，tokenize 报错的，具体需要根据你的环境来排查。
我自定义collate_fn函数是为了在Dataset 的初始化先 tokenize 文本，这样可以加快 get_item 的速度。在我自己的环境下没问题，所以你需要自己排查这一步是怎么回事。
明天我上传一份处理好的数据吧。

**Comment by ryy980622** [comment]
谢谢！如果有处理好的数据就最好了，另外可以麻烦你也把python和transformers的版本列出来吗？

**Comment by JarenceSJ** [comment]
这是Digitial_Music的[数据](https://drive.google.com/drive/folders/1OPkb_XLlxDp4otLy5-WKX4j_RvxODPuj?usp=sharing)。
python=3.8.3
transformers=3.1.0

**Comment by ryy980622** [comment]
非常感谢！transformers的版本调整后不再报错，但是我这边用您提供的Digitial_Music数据运行rgc.py只得到了如下的结果，与论文中report的结果相差较大，我看到论文中调的超参数都是针对rgc_nd_ed.py的，请问如何复现出论文中RG0.8037的结果呢？
Best Iter Idx=94, Best Valid RMSE=0.8850, Best Test RMSE=0.8978
另外我发现我自己生成的数据和您提供的数据是不一样的，请问这个会对实验结果造成很大影响吗？

**Comment by JarenceSJ** [comment]
论文中汇报的是 MSE 指标...。数据集划分不同会有影响的。

**Comment by ryy980622** [comment]
明白了，谢谢！

**Comment by FANJIYU0825** [comment]
想請問 
有完整的Word2vector.py跑程式得流程  
我現在卡在  Word2vector.py  找不到   cloth_5 數據
但是我換成 yelp2013  數據
